name: shallow
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.13.0
  - torchvision=0.14.0
  - pytorch-cuda=11.7
  - pip
  - pip:
    - transformers==4.23.1
    - diffusers==0.11.1
    - datasets
    - wandb
    - scipy
    - matplotlib
    - open-clip-torch
    - compressai
    - ftfy
    - regex
    - tqdm
    - accelerate
    - huggingface_hub